# Generated by Django 3.1.7 on 2021-05-27 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0031_project_project_image'),
        ('models', '0012_auto_20210526_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicModelObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj', models.FileField(upload_to='models/objects/')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='models.model')),
            ],
        ),
        migrations.CreateModel(
            name='PublishedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('model_obj', models.ManyToManyField(to='portal.PublicModelObject')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
