# Generated by Django 3.1.7 on 2021-05-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishedmodel',
            name='img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='models/image'),
        ),
    ]
