# Generated by Django 3.1.7 on 2021-07-02 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0035_auto_20210607_2049'),
        ('portal', '0002_publishedmodel_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishedmodel',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
