apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    run: {{ .Release.Name }}-mlflow
spec:
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
  selector:
    release: {{ .Release.Name }}