app_action: Create
app_id: ''
app_name: jupyter
appname: jupyter-lab-test-vry-7070
apps:
  environment:
    jupyter-sklearn:
      app_action: Create
      app_id: ''
      app_name: jupyter-sklearn
      appname: environment-test-vry-7a62
      appobj:
        jupyter-lab: true
      apps:
        docker_registry:
          registry:
            app_action: Create
            app_id: ''
            app_name: registry
            appname: docker-registry-test-vry-2d04
            apps:
              volume:
                regvol:
                  app_action: Create
                  app_id: ''
                  app_name: regvol
                  appname: volume-test-vry-84b1
                  apps: {}
                  chart: apps/volume
                  gatekeeper:
                    auth_endpoint: https://keycloak-dev.local.stackn.dev/auth/realms
                    client_id: volume-test-vry-84b1
                    client_secret: 5e1e19a8-62c4-457d-a6f9-f2c2c8e035cc
                    realm: STACKn
                    skip_tls: '0'
                  global:
                    domain: studio-dev.local.stackn.dev
                  namespace: studio-develop
                  permission: private
                  permissions:
                    private: true
                    project: false
                    public: false
                  project:
                    name: test
                    slug: test-vry
                  release: volume-test-vry-84b1
                  s3sync:
                    image: scaleoutsystems/s3-sync:latest
                  service:
                    name: volume-test-vry-84b1
                  storageClass: microk8s-hostpath
                  volume:
                    size: 20Gi
            chart: apps/docker-registry
            credentials:
              password: password
              username: admin
            gatekeeper:
              auth_endpoint: https://keycloak-dev.local.stackn.dev/auth/realms
              client_id: docker-registry-test-vry-2d04
              client_secret: 227f6655-b464-480b-a9c7-8a25e3441bd8
              realm: STACKn
              skip_tls: '0'
            global:
              domain: studio-dev.local.stackn.dev
            namespace: studio-develop
            permission: private
            permissions:
              private: true
              project: false
              public: false
            project:
              name: test
              slug: test-vry
            release: docker-registry-test-vry-2d04
            s3sync:
              image: scaleoutsystems/s3-sync:latest
            service:
              name: docker-registry-test-vry-2d04
            storageClass: microk8s-hostpath
      chart: apps/environment
      container:
        name: jupyter-sklearn
        tag: v1
      gatekeeper:
        auth_endpoint: https://keycloak-dev.local.stackn.dev/auth/realms
        client_id: environment-test-vry-7a62
        client_secret: dffcac69-dada-4a20-9bd1-6ac1a730a1d2
        realm: STACKn
        skip_tls: '0'
      global:
        domain: studio-dev.local.stackn.dev
      image:
        dockerfile: 'FROM jupyter/minimal-notebook:latest


          RUN pip install numpy matplotlib sklearn tensorflow'
      namespace: studio-develop
      permission: project
      permissions:
        private: false
        project: true
        public: false
      project:
        client_id: test-vry
        client_secret: 7b1e5a8f-93c7-4480-9237-6b9846ff0a21
      release: environment-test-vry-7a62
      s3sync:
        image: scaleoutsystems/s3-sync:latest
      service:
        name: environment-test-vry-7a62
      storageClass: microk8s-hostpath
  volume:
    mnist:
      app_action: Create
      app_id: ''
      app_name: mnist
      appname: volume-test-vry-8a79
      apps: {}
      chart: apps/volume
      gatekeeper:
        auth_endpoint: https://keycloak-dev.local.stackn.dev/auth/realms
        client_id: volume-test-vry-8a79
        client_secret: cad6a404-6001-4617-b648-8f964d7fe992
        realm: STACKn
        skip_tls: '0'
      global:
        domain: studio-dev.local.stackn.dev
      namespace: studio-develop
      permission: private
      permissions:
        private: true
        project: false
        public: false
      project:
        name: test
        slug: test-vry
      release: volume-test-vry-8a79
      s3sync:
        image: scaleoutsystems/s3-sync:latest
      service:
        name: volume-test-vry-8a79
      storageClass: microk8s-hostpath
      volume:
        size: 5Gi
chart: apps/lab-test
flavor:
  gpu:
    enabled: false
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 1000m
    memory: 2Gi
gatekeeper:
  auth_endpoint: https://keycloak-dev.local.stackn.dev/auth/realms
  client_id: jupyter-lab-test-vry-7070
  client_secret: 6be7f468-7e29-43ca-98a5-a60e10fedc3e
  realm: STACKn
  skip_tls: '0'
global:
  domain: studio-dev.local.stackn.dev
namespace: studio-develop
permission: private
permissions:
  private: true
  project: false
  public: false
project:
  name: test
  slug: test-vry
release: jupyter-lab-test-vry-7070
s3sync:
  image: scaleoutsystems/s3-sync:latest
service:
  name: jupyter-lab-test-vry-7070
storageClass: microk8s-hostpath
