kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-rp-config
  namespace: {{ .Values.namespace }}
data:
  # Configuration values can be set as key-value properties
  nginx.conf: |-
    worker_processes 1;
    events { worker_connections 1024; }
    http {
        server {
            listen 1234;

            client_max_body_size 100M;

            location ~ /api {
                auth_basic "MLFlow API";
                auth_basic_user_file /auth/htpasswd;
                proxy_pass http://127.0.0.1:5000;
            }

            location / {
                proxy_pass http://127.0.0.1:5000;
            }
            
        }
    }