
settings_file: project-settings
user_settings_file: user-settings
namespace: default
appname: jupyter-lab
project:
  name: project
  slug: project-slug
  
labs:
  image: scaleoutsystems/jupyter-stackn:v0.1.5

  resources:
    requests:
      memory: 512Mi
      cpu: 0.2
    limits:
      memory: 512Mi
      cpu: 0.2

  gpu:
    enabled: false

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: acceleration
            operator: In
            values:
            - gpu

global:
  domain: localhost

imagePullSecrets:
  - name: regcred

minio:
  access_key: minio
  secret_key: minio123
  bucket: dataset 

ingress:
  v1beta1: false
  secretName: prod-ingress

service:
  name: ""
  port: 80
  targetport: 8888

mlflow:
  url: ""
  s3url: ""
  access_key: ""
  secret_key: ""
  region: ""
  username: ""
  password: ""