{{ if .Values.ingress.v1beta1 }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-fed
  namespace: {{ .Values.namespace }}
  labels:
    io.kompose.service: {{ .Release.Name }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "5500m"
spec:
  rules:
    - host: fed-{{ .Release.Name }}.{{ .Values.global.domain }}
      http:
        paths:
        - path: /
          backend:
            serviceName: {{ .Release.Name }}-fed
            servicePort: 80
  tls:
    - secretName: {{ .Values.ingress.secretName }}
      hosts:
        - fed-{{ .Release.Name }}.{{ .Values.global.domain }}

{{ else }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-fed
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "5500m"
spec:
  rules:
    - host: fed-{{ .Release.Name }}.{{ .Values.global.domain }}
      http:
        paths:
        - path: /
          backend:
            service:
              name: {{ .Release.Name }}-fed
              port:
                number: 80
          pathType: ImplementationSpecific
  tls:
    - secretName: {{ .Values.ingress.secretName }}
      hosts:
        - fed-{{ .Release.Name }}.{{ .Values.global.domain }}

{{- end }}