kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-rp-config
  namespace: {{ .Values.namespace }}
data:
  # Configuration values can be set as key-value properties
  nginx.conf: |-
    worker_processes 1;
    events { worker_connections 1024; }
    http {
        server {
            listen 1234;

            client_max_body_size 500M;
            large_client_header_buffers 4 128k;

            # location ~* ^(\/_matrix|\/_synapse\/client) {
            #     proxy_pass http://127.0.0.1:8008;
            #     proxy_set_header X-Forwarded-For $remote_addr;
            #     proxy_set_header X-Forwarded-Proto $scheme;
            #     proxy_set_header Host $host;

            #     # Nginx by default only allows file uploads up to 1M in size
            #     # Increase client_max_body_size to match max_upload_size defined in homeserver.yaml
            #     client_max_body_size 500M;
            # }

            location / {
                proxy_pass http://127.0.0.1:8008;
                # proxy_set_header X-Forwarded-For $remote_addr;
                # proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header Host $host;

                # Nginx by default only allows file uploads up to 1M in size
                # Increase client_max_body_size to match max_upload_size defined in homeserver.yaml
                client_max_body_size 500M;
            }
            location /.well-known/matrix/server {
              add_header 'Content-Type' 'application/json charset=UTF-8';
              return 200 '{"m.server": "fed-{{ .Release.Name }}.{{ .Values.global.domain }}:443"}';
            }
        }
    }