apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-fed
  namespace: {{ .Values.namespace }}
  labels:
    run: {{ .Release.Name }}-fed
spec:
  ports:
  - port: 80
    targetPort: 8448
    protocol: TCP
  selector:
    release: {{ .Release.Name }}