kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-serv
  namespace: {{ .Values.namespace }}
data:
  server: |-
    {
        "m.server": "fed.{{ .Release.Name }}.{{ .Values.global.domain }}:443"
    }