apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appname }}
  namespace: {{ .Values.namespace }}
  labels:
    run: {{ .Values.appname }}
spec:
  ports:
  - port: 80
    targetPort: 9090
    protocol: TCP
  selector:
    release: {{ .Release.Name }}