apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appname }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appname }}
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      release: {{ .Release.Name }}
      app: fastapi-serve-volume
      project: {{ .Values.project.slug }}
      type: app
      pod: fastapi-serve-volume
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8501"
      labels:
        release: {{ .Release.Name }}
        app: fastapi-serve-volume
        project: {{ .Values.project.slug }}
        type: app
        pod: fastapi-serve-volume
    spec:
      volumes:
      - name: gatekeeper-config
        configMap:
          name: {{ .Release.Name }}-gatekeeper-config
      {{- range $key, $value := .Values.apps.volume }}
      - name: {{ $key }}
        persistentVolumeClaim:
          claimName: {{ $value.release }}
      {{- end }}
      imagePullSecrets:
        - name: {{ .Release.Name }}-pull-secret
      containers:
      - name: gatekeeper
        image: {{ .Values.gatekeeper.image }}
        imagePullPolicy: Always
        args:
          - --config=/etc/secrets/gatekeeper.yaml
        ports:
          - containerPort: {{ .Values.gatekeeper.port }}
        volumeMounts:
        - name: gatekeeper-config
          mountPath: /etc/secrets/
      - name: serve
        resources:
          limits:
            cpu: {{ .Values.flavor.limits.cpu }}
            memory: {{ .Values.flavor.limits.memory }}
          requests:
            cpu: {{ .Values.flavor.requests.cpu }}
            memory: {{ .Values.flavor.requests.memory }}
        volumeMounts:
        {{- range $key, $value := .Values.apps.volume }}
        - name: {{ $key }}
          mountPath: /{{ $key }}
        {{- end }}
        env:
        - name: MODEL_VOLUME
          value: {{ .Values.model_volume.path }}
        image: {{ .Values.environment.repository }}/{{ .Values.environment.image }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.deployment.port }}