apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: {{ .Release.Name }}
  name: {{ .Release.Name | replace "_" "-" }}
  namespace: {{ .Values.namespace }}
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-registry
      release: {{ .Release.Name }}
      project: {{ .Values.project.slug }}
      type: app
      pod: docker-registry
  template:
    metadata:
      labels:
        app: docker-registry
        release: {{ .Release.Name }}
        project: {{ .Values.project.slug }}
        type: app
        pod: docker-registry
    spec:
      initContainers:
      - image: alpine:latest
        name: init-auth
        command: ["/bin/sh"]
        args: ["-c", "apk add apache2-utils && htpasswd -Bbn {{ .Values.credentials.username }} {{ .Values.credentials.password }} > /auth/htpasswd"]
        volumeMounts:
        - name: auth-vol
          mountPath: /auth
      containers:
      - name: reverse-proxy
        image: nginx:alpine
        imagePullPolicy: Always
        volumeMounts:
        - name: rp-conf
          mountPath: /etc/nginx
      - name: gatekeeper
        image: {{ .Values.gatekeeper.image }}
        imagePullPolicy: Always
        args:
          - --config=/etc/secrets/gatekeeper.yaml
        ports:
          - containerPort: {{ .Values.gatekeeper.port }}
        volumeMounts:
        - name: gatekeeper-config
          mountPath: /etc/secrets/
      - image:  joxit/docker-registry-ui:static
        name: registry-ui
        env:
        - name: "REGISTRY_URL"
          value: "http://{{ .Release.Name }}:5000"
        - name: "REGISTRY_TITLE"
          value: "TEST"
        - name: "NGINX_PROXY_HEADER_Authorization"
          value: "Basic {{ tpl ("{{ .Values.credentials.username }}:{{ .Values.credentials.password }}") . | b64enc }}"
      - image: registry:2
        name: registry
        env:
        - name: "REGISTRY_AUTH"
          value: "htpasswd"
        - name: "REGISTRY_AUTH_HTPASSWD_REALM"
          value: "Registry Realm"
        - name: "REGISTRY_AUTH_HTPASSWD_PATH"
          value: /auth/htpasswd
        - name: "REGISTRY_HTTP_SECRET"
          value: "{{ .Release.Name }}"
        ports:
        - containerPort: 5000
        resources: {}
        volumeMounts:
        - name: auth-vol
          mountPath: /auth
        {{- range $key, $value := .Values.apps.volume }}
        - name: {{ $key }}
          mountPath: /var/lib/registry
        {{- end }}

      hostname: {{ .Release.Name }}
      restartPolicy: Always
      volumes:
      - name: auth-vol
        emptyDir: {}
      - name: rp-conf
        configMap:
          name: {{ .Release.Name }}-rp-config
      - name: gatekeeper-config
        configMap:
          name: {{ .Release.Name }}-gatekeeper
      {{- range $key, $value := .Values.apps.volume }}
      - name: {{ $key }}
        persistentVolumeClaim:
          claimName: {{ $value.release }}
      {{- end }}
status: {}
