apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.release }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.release }}
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      release: {{ .Values.release }}
      app: pebble-client
      project: {{ .Values.project.slug }}
      type: app
      pod: pebble-client
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8501"
      labels:
        release: {{ .Values.release }}
        app: pebble-client
        project: {{ .Values.project.slug }}
        type: app
        pod: pebble-client
    spec:  
      containers:
      - name: client
        image: scaleoutsystems/pebble-client:latest
        imagePullPolicy: Always
        env:
        {{- range $key, $val := .Values.apps.iotex }}
        - name: MQTT_HOST
          value: {{ $val.release }}
        - name: MQTT_PORT
          value: "1883"
        {{- end }}
        - name: PEBBLE_ID
          value: {{ .Values.release }}
        
