kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.release }}-minio
  namespace: {{ .Values.namespace }}
data:
  minio.json: |-
    {
        "endpoint": "{{ .Values.s3.host }}",
        "region": "{{ .Values.s3.region }}",
        "ak": "{{ .Values.s3.access_key }}",
        "sk": "{{ .Values.s3.secret_key }}",
        "ssl": true,
        "bucket": "pebble-store",
        "path": ""
    }
