apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.release }}
  namespace: {{ .Values.namespace }}
  labels:
    run: {{ .Values.release }}
spec:
  ports:
  - port: 1883
    targetPort: 1883
    protocol: TCP
  selector:
    release: {{ .Values.release }}