# Generated by Django 3.2.11 on 2022-01-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='path',
            field=models.CharField(blank=True, default='models', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='release_type',
            field=models.CharField(default='minor', max_length=255),
        ),
    ]
