# Generated by Django 3.2.11 on 2022-01-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_alter_model_release_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='release_type',
            field=models.CharField(choices=[('M', 'Major'), ('m', 'minor')], default='m', max_length=255),
        ),
    ]
