

volume:
  size: 2Gi

labs:
  image: jupyter/minimal-notebook:latest
  repository: ""
  secret: ""

global:
  domain: platform.local

minio:
  access_key: minio
  secret_key: minio123
  volume:
    size: 2Gi

defaultBucket:
  enabled: True
  policy: download

service:
  type: ClusterIP

# Registry for local images, e.g. model containers.
# Default host is registry.global.domain
# secure: False can be used for local testing

# NOTE: It seems like the internal host name doesn't work for deployment.
# I'm not sure why... Deployment expects the registry hostname to be
# registry.global.domain
registry:
  secure: False
  host: stack-docker-registry:5000

imagePullSecret: regcred
#storageClassName: aws-efs
serving_namespace: default #serving
settings_file: stackn-settings
