# Generated by Django 2.2.13 on 2020-08-31 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
                ('slug', models.CharField(max_length=512)),
                ('session_key', models.CharField(max_length=512)),
                ('session_secret', models.CharField(max_length=512)),
                ('settings', models.TextField()),
                ('chart', models.CharField(max_length=512)),
                ('helm_repo', models.CharField(blank=True, max_length=1024, null=True)),
                ('status', models.CharField(choices=[('CR', 'Created'), ('ST', 'Started'), ('ST', 'Stopped'), ('FN', 'Finished'), ('AB', 'Aborted')], default='CR', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lab_session_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_session_owner', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='projects.Project')),
            ],
        ),
    ]
