# Generated by Django 2.2.13 on 2020-09-01 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0001_initial'),
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='chart',
        ),
        migrations.RemoveField(
            model_name='session',
            name='session_key',
        ),
        migrations.RemoveField(
            model_name='session',
            name='session_secret',
        ),
        migrations.AddField(
            model_name='session',
            name='appname',
            field=models.CharField(default='app-default', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='environment_slug',
            field=models.CharField(default='slug', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='flavor_slug',
            field=models.CharField(default='slug', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='helmchart',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='deployments.HelmResource'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='keycloak_client_id',
            field=models.CharField(default='keycloak_client', max_length=512),
            preserve_default=False,
        ),
    ]
