# Generated by Django 2.2.13 on 2020-09-01 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_auto_20200901_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='settings',
        ),
    ]
