# Generated by Django 4.1.7 on 2023-03-10 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_apps_user_can_create'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appinstance',
            options={'permissions': [('can_access_app', 'Can access app service')]},
        ),
    ]
