# Generated by Django 4.1.7 on 2023-05-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_delete_apppermission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apps',
            name='logo_file',
        ),
        migrations.AddField(
            model_name='apps',
            name='user_can_delete',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='apps',
            name='user_can_edit',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='apps',
            name='logo',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
