# Generated by Django 4.1.7 on 2023-07-05 11:33

import tagulous.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_environment_public_projecttemplate_enabled_and_more'),
        ('apps', '0011_remove_apps_logo_file_apps_user_can_delete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appinstance',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, help_text='Enter a comma-separated tag string', to='apps.tagulous_appinstance_tags'),
        ),
        migrations.AlterField(
            model_name='apps',
            name='projects',
            field=models.ManyToManyField(blank=True, to='projects.project'),
        ),
    ]
