name: default

channels:
  - conda-forge

dependencies:
  - python=3.6
  - pip
  - ipykernel=5.3.4
  - pip:
    - mlflow
    - numpy==1.14.3
    - matplotlib==3.0.2
    - pandas==0.22.0
    - scipy
    - scikit-learn==0.19.1
    - cloudpickle==0.6.1
    - boto3
