namespace: default
appname: vscode
project:
  name: test
  slug: slug

gatekeeper:
  image: scaleoutsystems/gatekeeper:latest #registry.scilifelab.stackn.dev/keycloak-gatekeeper:latest #keycloak/keycloak-gatekeeper:latest
  realm: STACKn
  client_secret: 75ffdab1-605a-49a9-9544-4807072d0908
  client_id: wetty-test
  auth_endpoint: https://keycloak.local.stackn.dev/auth/realms
  skip_tls: 0

s3sync:
  image: registry.scilifelab.stackn.dev/s3-sync:latest #scaleoutsystems/s3-sync:latest

global:
  domain: local.stackn.dev

imagePullSecrets:
  - name: regcred


ingress:
  v1beta1: false
  secretName: prod-ingress

apps:
  mongodb:
    app_name:
      release: release-name
      volumes:
        vol_name:
          name: vol_name
          claim: vol_claim_name
      credentials:
        username: admin
        password: password
