# Generated by Django 4.1.7 on 2023-03-14 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppPermission',
        ),
    ]
