apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: "27017"
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetport }}
  selector:
    release: {{ .Release.Name }}
