# Generated by Django 2.2.13 on 2020-08-31 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('slug', models.CharField(blank=True, max_length=512, null=True)),
                ('image', models.CharField(max_length=512)),
                ('dockerfile', models.TextField(default='FROM jupyter/base-notebook')),
                ('startup', models.TextField(blank=True, null=True)),
                ('teardown', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('slug', models.CharField(max_length=512)),
                ('cpu', models.TextField(blank=True, null=True)),
                ('mem', models.TextField(blank=True, null=True)),
                ('gpu', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.CharField(max_length=512, unique=True)),
                ('image', models.CharField(blank=True, max_length=2048, null=True)),
                ('project_key', models.CharField(max_length=512)),
                ('project_secret', models.CharField(max_length=512)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repository', models.CharField(blank=True, max_length=512, null=True)),
                ('repository_imported', models.BooleanField(default=False)),
                ('clone_url', models.CharField(blank=True, max_length=512, null=True)),
                ('authorized', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('environment', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='projects.Environment')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('DE', 'deployments'), ('LA', 'labs'), ('MO', 'models'), ('PR', 'projects'), ('RE', 'reports'), ('UN', 'undefined')], default='UN', max_length=2)),
                ('headline', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
    ]
