# Generated by Django 3.2.11 on 2022-01-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttemplate',
            name='template',
            field=models.TextField(blank=True, null=True),
        ),
    ]
