# Generated by Django 2.2.13 on 2020-12-02 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0005_auto_20201029_2008'),
        ('projects', '0002_remove_project_environment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('slug', models.CharField(blank=True, max_length=512, null=True)),
                ('size', models.CharField(max_length=512)),
                ('project_slug', models.CharField(max_length=512)),
                ('created_by', models.CharField(max_length=512)),
                ('settings', models.TextField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('helmchart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='deployments.HelmResource')),
            ],
        ),
    ]
