# Generated by Django 3.2.11 on 2022-02-11 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projecttemplate_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='mlflow',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_mlflow', to='projects.mlflow'),
        ),
        migrations.AlterField(
            model_name='project',
            name='s3storage',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_s3', to='projects.s3'),
        ),
    ]
