# Generated by Django 2.2.13 on 2020-12-13 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cluster',
            field=models.CharField(default='Default', max_length=512),
        ),
    ]
