# Generated by Django 3.2.11 on 2022-06-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20220211_1613'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('can_view_project', 'Can view project')]},
        ),
        migrations.AddField(
            model_name='mlflow',
            name='host',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
