# Generated by Django 3.1.6 on 2021-02-24 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0003_volume'),
    ]

    operations = [
        migrations.CreateModel(
            name='S3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('host', django_cryptography.fields.encrypt(models.CharField(max_length=512))),
                ('access_key', django_cryptography.fields.encrypt(models.CharField(max_length=512))),
                ('secret_key', django_cryptography.fields.encrypt(models.CharField(max_length=512))),
                ('region', django_cryptography.fields.encrypt(models.CharField(max_length=512))),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s3_project', to='projects.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='s3storage',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_s3', to='projects.s3'),
        ),
    ]
