# Generated by Django 3.1.6 on 2021-02-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20210224_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s3',
            name='access_key',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='s3',
            name='host',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='s3',
            name='region',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='s3',
            name='secret_key',
            field=models.CharField(max_length=512),
        ),
    ]
