# Generated by Django 3.1.6 on 2021-02-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20210224_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s3',
            name='region',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
