# Generated by Django 3.1.6 on 2021-02-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20210224_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s3',
            name='region',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
