# Generated by Django 3.1.6 on 2021-02-24 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0041_auto_20210223_0918'),
        ('projects', '0008_auto_20210224_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='s3',
            name='app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.appinstance'),
        ),
    ]
