# Generated by Django 3.1.6 on 2021-02-24 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0041_auto_20210223_0918'),
        ('projects', '0010_auto_20210224_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s3',
            name='app',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='s3obj', to='apps.appinstance'),
        ),
    ]
