# Generated by Django 3.1.6 on 2021-02-26 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0041_auto_20210223_0918'),
        ('projects', '0011_auto_20210224_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='environment',
            name='dockerfile',
        ),
        migrations.RemoveField(
            model_name='environment',
            name='startup',
        ),
        migrations.RemoveField(
            model_name='environment',
            name='teardown',
        ),
        migrations.AddField(
            model_name='environment',
            name='app',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.apps'),
        ),
        migrations.AddField(
            model_name='environment',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AddField(
            model_name='environment',
            name='registry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='apps.apps'),
        ),
        migrations.AddField(
            model_name='environment',
            name='repository',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='environment',
            name='image',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='environment',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='environment',
            name='slug',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
