# Generated by Django 3.1.6 on 2021-02-26 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0041_auto_20210223_0918'),
        ('projects', '0012_auto_20210226_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='registry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='apps.appinstance'),
        ),
    ]
