# Generated by Django 3.1.6 on 2021-03-01 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20210301_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flavor',
            name='slug',
        ),
    ]
