# Generated by Django 3.1.6 on 2021-03-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_remove_flavor_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('template', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Volume',
        ),
    ]
