# Generated by Django 3.1.6 on 2021-03-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20210308_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttemplate',
            name='template',
            field=models.TextField(blank=True, null=True),
        ),
    ]
