# Generated by Django 3.1.6 on 2021-03-18 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0020_auto_20210318_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlflow',
            name='ba_password',
        ),
        migrations.RemoveField(
            model_name='mlflow',
            name='ba_username',
        ),
        migrations.CreateModel(
            name='BasicAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('username', models.CharField(blank=True, default='', max_length=100)),
                ('password', models.CharField(blank=True, default='', max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='mlflow',
            name='basic_auth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projects.basicauth'),
        ),
    ]
