# Generated by Django 3.1.6 on 2021-03-18 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_auto_20210318_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicauth',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ba_project', to='projects.project'),
        ),
    ]
