# Generated by Django 3.1.6 on 2021-03-18 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_basicauth_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='mlflow',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_mlflow', to='projects.mlflow'),
        ),
    ]
