# Generated by Django 3.1.6 on 2021-03-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_project_mlflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, default='active', max_length=20, null=True),
        ),
    ]
