# Generated by Django 3.1.7 on 2021-04-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_auto_20210319_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttemplate',
            name='slug',
            field=models.CharField(default='', max_length=512),
        ),
    ]
