# Generated by Django 3.1.7 on 2021-04-09 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0049_auto_20210318_1401'),
        ('projects', '0027_releasename'),
    ]

    operations = [
        migrations.AddField(
            model_name='releasename',
            name='app',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.apps'),
        ),
    ]
