# Generated by Django 3.1.7 on 2021-05-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_auto_20210409_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='projects/images/'),
        ),
    ]
