# Generated by Django 3.1.7 on 2021-06-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_project_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttemplate',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='projecttemplates/images/'),
        ),
    ]
