# Generated by Django 3.1.7 on 2021-06-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_projecttemplate_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttemplate',
            name='revision',
            field=models.IntegerField(default=1),
        ),
    ]
