# Generated by Django 3.1.7 on 2021-06-07 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_projecttemplate_revision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttemplate',
            name='name',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='projecttemplate',
            name='slug',
            field=models.CharField(default='', max_length=512, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='projecttemplate',
            unique_together={('slug', 'revision')},
        ),
    ]
