
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-project-settings-configmap
data:
  # Configuration values can be set as key-value properties
  stackn.yaml: |- 
{{ .Values.settings_file | indent 4 }}