# Default values for combiner.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
domain: 192.168.64.2.nip.io
global:
  network: fedn-network
  control:
    helper: keras_weights
replicaCount: 1

ingress:
  secretName: prod-ingress