# Generated by Django 2.2.13 on 2020-12-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='storageclass',
            field=models.CharField(default='microk8s-hostpath', max_length=512),
        ),
    ]
