# Generated by Django 2.2.13 on 2020-12-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0003_auto_20201215_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='load',
            field=models.TextField(default=''),
        ),
    ]
