# Generated by Django 2.2.13 on 2021-01-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0004_cluster_load'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='helmchart_id',
            field=models.IntegerField(default=-1),
        ),
    ]
