{{ if .Values.ingress.v1beta1 }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-body-size: "500m"
    nginx.ingress.kubernetes.io/auth-url: "http://{{ .Values.global.auth_domain }}:8080/auth/?project={{ .Values.project.slug }}"
    nginx.ingress.kubernetes.io/auth-signin: "http://{{ .Values.global.domain }}:8080/accounts/login/?next=$scheme%3A%2F%2F$host"
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Values.namespace }}
spec:
  rules:
    - host: {{ .Release.Name }}.{{ .Values.global.domain }}
      http:
        paths:
        - path: /
          backend:
            serviceName: {{ $.Release.Name }}-{{ .Values.appname }}-svc
            servicePort: 80
  tls:
    - secretName: prod-ingress
      hosts:
        - {{ .Release.Name }}.{{ .Values.global.domain }}
{{ else }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-body-size: "500m"
    nginx.ingress.kubernetes.io/auth-url: "http://{{ .Values.global.auth_domain }}:8080/auth/?project={{ .Values.project.slug }}"
    nginx.ingress.kubernetes.io/auth-signin: "http://{{ .Values.global.domain }}:8080/accounts/login/?next=$scheme%3A%2F%2F$host"
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Values.namespace }}
spec:
  rules:
    - host: {{ .Release.Name }}.{{ .Values.global.domain }}
      http:
        paths:
        - path: /
          backend:
            service:
              name: {{ $.Release.Name }}-{{ .Values.appname }}-svc
              port:
                number: 80
          pathType: ImplementationSpecific
  tls:
    - secretName: prod-ingress
      hosts:
        - {{ .Release.Name }}.{{ .Values.global.domain }}

{{- end }}