{{ if .Values.ingress.v1beta1 }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "20000m"
    nginx.ingress.kubernetes.io/auth-url: "http://{{ .Values.global.domain }}:8080/auth/?project={{ .Values.project.slug }}"
    nginx.ingress.kubernetes.io/auth-signin: "http://{{ .Values.global.domain }}:8080/accounts/login/?next=$scheme%3A%2F%2F$host"
    #nginx.ingress.kubernetes.io/auth-response-headers: X-Forwarded-Host
  name: {{ .Release.Name }}-minio
  namespace: {{ .Values.namespace }}
spec:
  rules:
    - host: {{ .Release.Name }}.{{ .Values.global.domain }}
      http:
        paths:
        - path: /
          backend:
            serviceName: {{ .Values.service.name }}
            servicePort: 9001
  tls:
    - secretName: prod-ingress
      hosts:
        - {{ .Values.global.domain }}
{{ else }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "20000m"
    nginx.ingress.kubernetes.io/auth-url: "http://{{ .Values.global.domain }}:8080/auth/?project={{ .Values.project.slug }}"
    nginx.ingress.kubernetes.io/auth-signin: "http://{{ .Values.global.domain }}:8080/accounts/login/?next=$scheme%3A%2F%2F$host"
    #nginx.ingress.kubernetes.io/auth-response-headers: X-Forwarded-Host
  name: {{ .Release.Name }}-minio
  namespace: {{ .Values.namespace }}
spec:
  rules:
    - host: {{ .Release.Name }}.{{ .Values.global.domain }}
      http:
        paths:
        - path: /
          backend:
            service:
              name: {{ .Values.service.name }}
              port:
                number: 9001
          pathType: ImplementationSpecific
  tls:
    - secretName: {{ .Values.ingress.secretName }}
      hosts:
        - {{ .Values.global.domain }}

{{ end }}