{{ if .Values.ingress.v1beta1 }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "http://{{ .Values.global.domain }}/auth"
    nginx.ingress.kubernetes.io/auth-signin: "http://{{ .Values.global.domain }}/auth/start?rd=$escaped_request_uri"
spec:
  rules:
    - host: {{ .Release.Name }}.{{ .Values.global.domain }}
      http:
        paths:
        - path: /
          backend:
            serviceName: {{ .Release.Name }}
            servicePort: 80
  tls:
    - secretName: {{ .Values.ingress.secretName }}
      hosts:
        - {{ .Values.global.domain }}
{{ else }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "http://{{ .Values.global.domain }}/auth"
    nginx.ingress.kubernetes.io/auth-signin: "http://{{ .Values.global.domain }}/auth/start?rd=$escaped_request_uri"
spec:
  rules:
    - host: {{ .Release.Name }}.{{ .Values.global.domain }}
      http:
        paths:
        - path: /
          backend:
            service:
              name: {{ .Release.Name }}
              port:
                number: 80
          pathType: ImplementationSpecific
  tls:
    - secretName: {{ .Values.ingress.secretName }}
      hosts:
        - {{ .Values.global.domain }}

{{- end }}