# Generated by Django 3.2.7 on 2021-09-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestaccount',
            name='email',
            field=models.EmailField(default='noemail@email.com', max_length=254),
            preserve_default=False,
        ),
    ]
