settings_file: project-settings
user_settings_file: user-settings
namespace: default

backup:
  bucket: backups

cronjob:
  schedule: "* * * * *"

resources:
  gpu:
    enabled: false
  limits:
    cpu: 1000m
    memory: 8Gi
  requests:
    cpu: 50m
    memory: 256Mi
    gpu: 0
  

iscron: false
