apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.scheduler.port }}
    targetPort: {{ .Values.scheduler.port }}
    protocol: TCP
  selector:
    target: {{ .Release.Name }}-dask-scheduler