# Generated by Django 4.1.7 on 2023-05-11 12:04

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20220602_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_image',
        ),
        migrations.AddField(
            model_name='project',
            name='apps_per_project',
            field=models.JSONField(blank=True, default=projects.models.get_default_apps_per_project_limit, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='pattern',
            field=models.CharField(default='', max_length=255),
        ),
    ]
