# Generated by Django 4.1.7 on 2023-07-05 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_project_project_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='environment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AlterField(
            model_name='environment',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
