apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name | replace "_" "-" }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: 80
    targetPort: {{ .Values.gatekeeper.port }}
    protocol: TCP
  selector:
    app: {{ .Release.Name }}
