# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: alliance.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='alliance.proto',
  package='grpc',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0e\x61lliance.proto\x12\x04grpc\",\n\x08Response\x12\x0e\n\x06\x63lient\x18\x01 \x01(\t\x12\x10\n\x08response\x18\x02 \x01(\t\"(\n\x06Status\x12\x0e\n\x06\x63lient\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"\xed\x01\n\x07Request\x12\x0e\n\x06\x63lient\x18\x01 \x01(\t\x12*\n\x07\x63ommand\x18\x02 \x01(\x0e\x32\x19.grpc.Request.RequestType\x12\x0f\n\x07payload\x18\x03 \x01(\t\x12\r\n\x05\x65xtra\x18\x04 \x01(\t\x12\x11\n\tto_client\x18\x05 \x01(\t\"s\n\x0bRequestType\x12\x0b\n\x07\x43ONNECT\x10\x00\x12\t\n\x05TRAIN\x10\x01\x12\x0c\n\x08VALIDATE\x10\x02\x12\x08\n\x04VOTE\x10\x03\x12\x0f\n\x0bGLOBALMODEL\x10\x04\x12\t\n\x05MODEL\x10\x05\x12\t\n\x05SCORE\x10\x06\x12\r\n\tHEARTBEAT\x10\x07\".\n\tHeartbeat\x12\x0e\n\x06\x63lient\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\t\"\x1c\n\nClientList\x12\x0e\n\x06\x63lient\x18\x01 \x03(\t2\xcd\x01\n\x0e\x41llianceServer\x12\x31\n\x0e\x41llianceStream\x12\x0e.grpc.Response\x1a\r.grpc.Request0\x01\x12,\n\x0bSendRequest\x12\r.grpc.Request\x1a\x0e.grpc.Response\x12*\n\nSendStatus\x12\x0c.grpc.Status\x1a\x0e.grpc.Response\x12.\n\x0bListClients\x12\r.grpc.Request\x1a\x10.grpc.ClientListb\x06proto3')
)



_REQUEST_REQUESTTYPE = _descriptor.EnumDescriptor(
  name='RequestType',
  full_name='grpc.Request.RequestType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CONNECT', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRAIN', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VALIDATE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VOTE', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GLOBALMODEL', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MODEL', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SCORE', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HEARTBEAT', index=7, number=7,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=235,
  serialized_end=350,
)
_sym_db.RegisterEnumDescriptor(_REQUEST_REQUESTTYPE)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='grpc.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='client', full_name='grpc.Response.client', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='response', full_name='grpc.Response.response', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=68,
)


_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='grpc.Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='client', full_name='grpc.Status.client', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='grpc.Status.status', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=110,
)


_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='grpc.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='client', full_name='grpc.Request.client', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='command', full_name='grpc.Request.command', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload', full_name='grpc.Request.payload', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='extra', full_name='grpc.Request.extra', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='to_client', full_name='grpc.Request.to_client', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _REQUEST_REQUESTTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=350,
)


_HEARTBEAT = _descriptor.Descriptor(
  name='Heartbeat',
  full_name='grpc.Heartbeat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='client', full_name='grpc.Heartbeat.client', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='grpc.Heartbeat.timestamp', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=352,
  serialized_end=398,
)


_CLIENTLIST = _descriptor.Descriptor(
  name='ClientList',
  full_name='grpc.ClientList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='client', full_name='grpc.ClientList.client', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=400,
  serialized_end=428,
)

_REQUEST.fields_by_name['command'].enum_type = _REQUEST_REQUESTTYPE
_REQUEST_REQUESTTYPE.containing_type = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Heartbeat'] = _HEARTBEAT
DESCRIPTOR.message_types_by_name['ClientList'] = _CLIENTLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'alliance_pb2'
  # @@protoc_insertion_point(class_scope:grpc.Response)
  })
_sym_db.RegisterMessage(Response)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), {
  'DESCRIPTOR' : _STATUS,
  '__module__' : 'alliance_pb2'
  # @@protoc_insertion_point(class_scope:grpc.Status)
  })
_sym_db.RegisterMessage(Status)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'alliance_pb2'
  # @@protoc_insertion_point(class_scope:grpc.Request)
  })
_sym_db.RegisterMessage(Request)

Heartbeat = _reflection.GeneratedProtocolMessageType('Heartbeat', (_message.Message,), {
  'DESCRIPTOR' : _HEARTBEAT,
  '__module__' : 'alliance_pb2'
  # @@protoc_insertion_point(class_scope:grpc.Heartbeat)
  })
_sym_db.RegisterMessage(Heartbeat)

ClientList = _reflection.GeneratedProtocolMessageType('ClientList', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTLIST,
  '__module__' : 'alliance_pb2'
  # @@protoc_insertion_point(class_scope:grpc.ClientList)
  })
_sym_db.RegisterMessage(ClientList)



_ALLIANCESERVER = _descriptor.ServiceDescriptor(
  name='AllianceServer',
  full_name='grpc.AllianceServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=431,
  serialized_end=636,
  methods=[
  _descriptor.MethodDescriptor(
    name='AllianceStream',
    full_name='grpc.AllianceServer.AllianceStream',
    index=0,
    containing_service=None,
    input_type=_RESPONSE,
    output_type=_REQUEST,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendRequest',
    full_name='grpc.AllianceServer.SendRequest',
    index=1,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendStatus',
    full_name='grpc.AllianceServer.SendStatus',
    index=2,
    containing_service=None,
    input_type=_STATUS,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ListClients',
    full_name='grpc.AllianceServer.ListClients',
    index=3,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_CLIENTLIST,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ALLIANCESERVER)

DESCRIPTOR.services_by_name['AllianceServer'] = _ALLIANCESERVER

# @@protoc_insertion_point(module_scope)
