# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import alliance_pb2 as alliance__pb2


class AllianceServerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.AllianceStream = channel.unary_stream(
        '/grpc.AllianceServer/AllianceStream',
        request_serializer=alliance__pb2.Response.SerializeToString,
        response_deserializer=alliance__pb2.Request.FromString,
        )
    self.SendRequest = channel.unary_unary(
        '/grpc.AllianceServer/SendRequest',
        request_serializer=alliance__pb2.Request.SerializeToString,
        response_deserializer=alliance__pb2.Response.FromString,
        )
    self.SendStatus = channel.unary_unary(
        '/grpc.AllianceServer/SendStatus',
        request_serializer=alliance__pb2.Status.SerializeToString,
        response_deserializer=alliance__pb2.Response.FromString,
        )
    self.ListClients = channel.unary_unary(
        '/grpc.AllianceServer/ListClients',
        request_serializer=alliance__pb2.Request.SerializeToString,
        response_deserializer=alliance__pb2.ClientList.FromString,
        )


class AllianceServerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def AllianceStream(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendRequest(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendStatus(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListClients(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AllianceServerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'AllianceStream': grpc.unary_stream_rpc_method_handler(
          servicer.AllianceStream,
          request_deserializer=alliance__pb2.Response.FromString,
          response_serializer=alliance__pb2.Request.SerializeToString,
      ),
      'SendRequest': grpc.unary_unary_rpc_method_handler(
          servicer.SendRequest,
          request_deserializer=alliance__pb2.Request.FromString,
          response_serializer=alliance__pb2.Response.SerializeToString,
      ),
      'SendStatus': grpc.unary_unary_rpc_method_handler(
          servicer.SendStatus,
          request_deserializer=alliance__pb2.Status.FromString,
          response_serializer=alliance__pb2.Response.SerializeToString,
      ),
      'ListClients': grpc.unary_unary_rpc_method_handler(
          servicer.ListClients,
          request_deserializer=alliance__pb2.Request.FromString,
          response_serializer=alliance__pb2.ClientList.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'grpc.AllianceServer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
