apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Values.namespace }}
  labels:
    io.kompose.service: {{ .Release.Name }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "5500m"
    nginx.ingress.kubernetes.io/auth-url: "http://{{ .Values.global.domain }}/auth"
    nginx.ingress.kubernetes.io/auth-signin: "http://{{ .Values.global.domain }}/auth/start?rd=$escaped_request_uri"
spec:
  rules:
    - host: {{ .Release.Name }}.{{ .Values.global.domain }}
      http:
        paths:
        - path: /
          backend:
            serviceName: {{ .Release.Name }}-keycloak-proxy-svc
            servicePort: 80
  tls:
    - secretName: {{ .Values.ingress.secretName }}
      hosts:
        - {{ .Release.Name }}.{{ .Values.global.domain }}