# Generated by Django 4.1.7 on 2023-05-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publishedmodel',
            name='img',
        ),
        migrations.AddField(
            model_name='publishedmodel',
            name='pattern',
            field=models.CharField(default='', max_length=255),
        ),
    ]
