kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name | replace "_" "-" }}-rp-config
  namespace: {{ .Values.namespace }}
data:
  # Configuration values can be set as key-value properties
  nginx.conf: |-
    worker_processes 1;
    events { worker_connections 1024; }

    http {
      map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
      }
      server {
        listen 80;

        client_max_body_size 0; # Disables checking of client request body size

        location / {
          proxy_set_header X-RSC-Request $scheme://$host:$server_port$request_uri;
          proxy_pass http://localhost:8787;
          proxy_set_header Host {{ .Release.Name }}.{{ .Values.global.domain }};
          proxy_set_header X-Forwarded-For $remote_addr;
          proxy_http_version 1.1;
          proxy_buffering off; # Required for XHR-streaming
        }
      }
    }