apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.release }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: grpc
      port: 443
      targetPort: 443
  selector:
    release: {{ .Values.release }}
status:
  loadBalancer: {}
