apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
  name: {{ .Values.release }}
  namespace: {{ .Values.namespace }}
spec:
  rules:
  - host: {{ .Values.release }}.{{ .Values.global.domain }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: {{ .Values.release }}
            port:
              name: grpc