apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: "9000"
    port: 27017
    targetPort: 27017
  selector:
    release: {{ .Release.Name }}
