# Generated by Django 2.2.13 on 2020-08-31 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeploymentDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access', models.CharField(choices=[('PR', 'Private'), ('PU', 'Public')], default='PR', max_length=2)),
                ('name', models.CharField(max_length=512, unique=True)),
                ('bucket', models.CharField(blank=True, max_length=512, null=True)),
                ('filename', models.CharField(blank=True, max_length=512, null=True)),
                ('image', models.CharField(blank=True, max_length=512, null=True)),
                ('path_predict', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_owner', to='projects.Project')),
            ],
        ),
        migrations.CreateModel(
            name='HelmResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('namespace', models.CharField(max_length=512)),
                ('chart', models.CharField(max_length=512)),
                ('params', models.CharField(max_length=2048)),
                ('username', models.CharField(max_length=512)),
                ('status', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeploymentInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appname', models.CharField(max_length=512)),
                ('access', models.CharField(choices=[('PR', 'Private'), ('LI', 'Limited'), ('PU', 'Public')], default='PR', max_length=2)),
                ('endpoint', models.CharField(max_length=512)),
                ('path', models.CharField(max_length=512)),
                ('release', models.CharField(max_length=512)),
                ('created_by', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployments.DeploymentDefinition')),
                ('helmchart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='deployments.HelmResource')),
                ('model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deployed_model', to='models.Model')),
            ],
        ),
    ]
