# Generated by Django 2.2.13 on 2020-09-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helmresource',
            name='params',
            field=models.CharField(max_length=4096),
        ),
    ]
