# Generated by Django 2.2.13 on 2020-09-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0002_auto_20200901_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helmresource',
            name='params',
            field=models.CharField(max_length=10000),
        ),
    ]
