# Generated by Django 2.2.13 on 2020-10-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0004_auto_20201021_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploymentinstance',
            name='created_by',
            field=models.CharField(max_length=512),
        ),
    ]
