# Generated by Django 2.2.13 on 2020-12-10 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0005_auto_20201029_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='helmresource',
            name='cluster',
            field=models.CharField(default='', max_length=512),
        ),
    ]
