# Generated by Django 2.2.13 on 2021-02-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0005_auto_20201029_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helmresource',
            name='params',
            field=models.CharField(max_length=100000),
        ),
    ]
