# Generated by Django 3.1.6 on 2021-02-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0006_auto_20210217_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helmresource',
            name='params',
            field=models.JSONField(),
        ),
    ]
