# Generated by Django 2.2.13 on 2021-01-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0006_helmresource_cluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='helmresource',
            name='info',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
