# Generated by Django 3.1.6 on 2021-03-09 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0007_auto_20210219_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deploymentinstance',
            name='deployment',
        ),
        migrations.RemoveField(
            model_name='deploymentinstance',
            name='helmchart',
        ),
        migrations.RemoveField(
            model_name='deploymentinstance',
            name='model',
        ),
        migrations.DeleteModel(
            name='DeploymentDefinition',
        ),
        migrations.DeleteModel(
            name='DeploymentInstance',
        ),
        migrations.DeleteModel(
            name='HelmResource',
        ),
    ]
