# Generated by Django 2.2.13 on 2020-11-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_to_log', models.CharField(default='Some model', max_length=32)),
                ('run_id', models.CharField(max_length=32)),
                ('run_created_at', models.DateField()),
                ('run_duration', models.CharField(max_length=255)),
                ('current_git_commit', models.CharField(max_length=255)),
                ('current_git_repo', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('CR', 'Created'), ('ON', 'Ongoing'), ('FI', 'Finished'), ('AR', 'Archived')], default='CR', max_length=2)),
            ],
            options={
                'unique_together': {('model_to_log', 'run_id')},
            },
        ),
    ]
