# Generated by Django 4.0 on 2021-12-13 08:51

from django.db import migrations, models
import django.db.models.deletion
import tagulous.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('models', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='docker_image',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.environment'),
        ),
        migrations.AddField(
            model_name='model',
            name='object_type',
            field=models.ManyToManyField(blank=True, to='models.ObjectType'),
        ),
        migrations.AddField(
            model_name='model',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_owner', to='projects.project'),
        ),
        migrations.AddField(
            model_name='model',
            name='s3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.s3'),
        ),
        migrations.AddField(
            model_name='model',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, help_text='Enter a comma-separated tag string', to='models.Tagulous_Model_tags'),
        ),
        migrations.AlterUniqueTogether(
            name='metadata',
            unique_together={('run_id', 'trained_model')},
        ),
        migrations.AlterUniqueTogether(
            name='model',
            unique_together={('name', 'version', 'project')},
        ),
    ]
