# Generated by Django 2.2.13 on 2020-11-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_modellog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modellog',
            old_name='model_to_log',
            new_name='trained_model',
        ),
        migrations.RenameField(
            model_name='modellog',
            old_name='run_duration',
            new_name='training_duration',
        ),
        migrations.RenameField(
            model_name='modellog',
            old_name='run_created_at',
            new_name='training_started_at',
        ),
        migrations.RenameField(
            model_name='modellog',
            old_name='run_id',
            new_name='uid',
        ),
        migrations.AddField(
            model_name='modellog',
            name='training_status',
            field=models.CharField(choices=[('ST', 'Started'), ('DO', 'Done'), ('FA', 'Failed')], default='ST', max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='modellog',
            unique_together={('uid', 'trained_model')},
        ),
        migrations.RemoveField(
            model_name='modellog',
            name='status',
        ),
    ]
