# Generated by Django 2.2.13 on 2020-11-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_modellog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modellog',
            old_name='run_duration',
            new_name='training_started_at',
        ),
        migrations.RenameField(
            model_name='modellog',
            old_name='run_id',
            new_name='uid',
        ),
        migrations.AddField(
            model_name='modellog',
            name='cpu_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='modellog',
            name='execution_time',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='modellog',
            name='latest_git_commit',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='modellog',
            name='miscellaneous',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='modellog',
            name='project',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='modellog',
            name='system_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='modellog',
            name='trained_model',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='modellog',
            name='training_status',
            field=models.CharField(choices=[('ST', 'Started'), ('DO', 'Done'), ('FA', 'Failed')], default='ST', max_length=2),
        ),
        migrations.AlterField(
            model_name='modellog',
            name='current_git_repo',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='modellog',
            unique_together={('uid', 'trained_model')},
        ),
        migrations.RemoveField(
            model_name='modellog',
            name='current_git_commit',
        ),
        migrations.RemoveField(
            model_name='modellog',
            name='model_to_log',
        ),
        migrations.RemoveField(
            model_name='modellog',
            name='run_created_at',
        ),
        migrations.RemoveField(
            model_name='modellog',
            name='status',
        ),
    ]
