# Generated by Django 2.2.13 on 2020-12-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_metadata_modellog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metadata',
            options={'verbose_name_plural': 'metadata'},
        ),
        migrations.AlterField(
            model_name='modellog',
            name='training_started_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
