# Generated by Django 3.1.6 on 2021-02-24 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20210224_1302'),
        ('models', '0002_metadata_modellog'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='s3',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.s3'),
        ),
    ]
