# Generated by Django 2.2.13 on 2020-12-12 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_auto_20201212_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='modellog',
            name='model_version',
            field=models.CharField(default='', max_length=255),
        ),
    ]
