# Generated by Django 3.1.6 on 2021-03-09 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20210308_2132'),
        ('models', '0003_model_s3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='s3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.s3'),
        ),
    ]
