# Generated by Django 2.2.13 on 2020-11-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_auto_20201111_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='modellog',
            name='endpoint',
            field=models.CharField(default='', max_length=512),
        ),
    ]
