# Generated by Django 2.2.13 on 2020-11-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_auto_20201116_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modellog',
            name='training_started_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
