# Generated by Django 3.2.11 on 2022-01-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_alter_model_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='release_type',
            field=models.CharField(choices=[('MAJOR', 'Major'), ('MINOR', 'minor')], default='minor', max_length=255),
        ),
    ]
