# Generated by Django 2.2.13 on 2021-01-20 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_modellog_model_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modellog',
            name='code_version',
        ),
    ]
