# Generated by Django 2.2.13 on 2020-11-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_auto_20201116_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modellog',
            name='miscellaneous',
            field=models.TextField(blank=True),
        ),
    ]
