# Generated by Django 3.1.6 on 2021-03-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0048_auto_20210310_1919'),
        ('models', '0004_auto_20210309_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('apps', models.ManyToManyField(blank=True, null=True, to='apps.Apps')),
            ],
        ),
        migrations.AddField(
            model_name='model',
            name='object_type',
            field=models.ManyToManyField(blank=True, null=True, to='models.ObjectType'),
        ),
    ]
