# Generated by Django 2.2.13 on 2020-11-12 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_auto_20201112_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modellog',
            name='trained_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Model'),
        ),
    ]
