# Generated by Django 2.2.13 on 2020-11-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_auto_20201116_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='modellog',
            name='metadata',
            field=models.TextField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='modellog',
            unique_together={('uid', 'trained_model', 'metadata')},
        ),
        migrations.RemoveField(
            model_name='modellog',
            name='miscellaneous',
        ),
    ]
