# Generated by Django 3.1.6 on 2021-03-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0048_auto_20210310_1919'),
        ('models', '0006_auto_20210313_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objecttype',
            name='apps',
            field=models.ManyToManyField(blank=True, to='apps.Apps'),
        ),
    ]
