# Generated by Django 2.2.13 on 2020-11-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_auto_20201117_0828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modellog',
            old_name='cpu_info',
            new_name='cpu_details',
        ),
        migrations.RenameField(
            model_name='modellog',
            old_name='uid',
            new_name='run_id',
        ),
        migrations.RenameField(
            model_name='modellog',
            old_name='system_info',
            new_name='system_details',
        ),
        migrations.AddField(
            model_name='modellog',
            name='code_version',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='modellog',
            unique_together={('run_id', 'trained_model')},
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(max_length=32)),
                ('trained_model', models.CharField(default='', max_length=32)),
                ('project', models.CharField(default='', max_length=255)),
                ('model_details', models.TextField(blank=True)),
                ('parameters', models.TextField(blank=True)),
                ('metrics', models.TextField(blank=True)),
            ],
            options={
                'unique_together': {('run_id', 'trained_model')},
            },
        ),
        migrations.RemoveField(
            model_name='modellog',
            name='metadata',
        ),
    ]
