# Generated by Django 2.2.13 on 2020-11-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_auto_20201112_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modellog',
            name='training_duration',
        ),
        migrations.AddField(
            model_name='modellog',
            name='cpu_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='modellog',
            name='execution_time',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='modellog',
            name='system_info',
            field=models.TextField(blank=True),
        ),
    ]
