# Generated by Django 3.1.6 on 2021-03-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_auto_20210313_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='object_type',
            field=models.ManyToManyField(blank=True, to='models.ObjectType'),
        ),
    ]
