# Generated by Django 2.2.13 on 2020-11-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_auto_20201112_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modellog',
            name='endpoint',
        ),
        migrations.AlterField(
            model_name='modellog',
            name='current_git_commit',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='modellog',
            name='current_git_repo',
            field=models.CharField(default='', max_length=255),
        ),
    ]
