# Generated by Django 3.1.6 on 2021-03-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_auto_20210313_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='bucket',
            field=models.CharField(blank=True, default='models', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='path',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
