# Generated by Django 2.2.13 on 2020-11-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0009_auto_20201113_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='modellog',
            name='miscellaneous',
            field=models.CharField(default='', max_length=255),
        ),
    ]
