# Generated by Django 3.1 on 2021-04-30 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0009_auto_20210318_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='model_card',
            field=models.TextField(blank=True, null=True),
        ),
    ]
