# Generated by Django 3.1.6 on 2021-05-10 14:15

from django.db import migrations, models
import django.db.models.deletion
import models.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_auto_20210409_1441'),
        ('models', '0010_model_model_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='model_card_headline',
            field=models.ImageField(blank=True, default=None, null=True,
                                    upload_to=models.models.upload_headline_path),
        ),
        migrations.AddField(
            model_name='model',
            name='docker_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       to='projects.environment', default=None),
        ),
    ]
