# Generated by Django 3.1.7 on 2021-05-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0011_auto_20210510_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='model_card_headline',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='models/image'),
        ),
    ]
