apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-minio
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: "9000"
    port: 9000
    targetPort: 9000
    {{- with .Values.service }}
    nodePort: {{ .minio }}
    {{- end }}
  selector:
    release: {{ .Release.Name }}

