{{ if .Values.environment.registry.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-pull-secret
  namespace: {{ .Values.namespace }}
stringData:
  .dockerconfigjson: |-
    {
      "auths": {
        "{{ .Values.environment.registry.release }}.{{ .Values.environment.registry.global.domain }}": {
          "auth": "{{ tpl ("{{ .Values.environment.registry.credentials.username }}:{{ .Values.environment.registry.credentials.password }}") $ | b64enc }}"
        }
      }
    }
type: kubernetes.io/dockerconfigjson
{{ end }}