apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appname }}
  namespace: {{ .Values.namespace }}
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      release: {{ .Release.Name }}
      app: dash-deployment
      project: {{ .Values.project.slug }}
      type: app
      pod: dash
  template:
    metadata:
      labels:
        release: {{ .Release.Name }}
        app: dash-deployment
        project: {{ .Values.project.slug }}
        type: app
        pod: dash
    spec:
      containers:
      - name: gatekeeper
        image: scaleoutsystems/gatekeeper:latest
        imagePullPolicy: Always
        args:
          - --config=/etc/secrets/gatekeeper.yaml
        ports:
          - containerPort: 9090
        volumeMounts:
        - name: gatekeeper-config
          mountPath: /etc/secrets/
      - name: dash
        image: scaleoutsystems/dash:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8050
        env:
        {{ if .Values.deployment.debug }}
        - name: DEBUG
          value: "true"
        {{ else }}
        - name: DEBUG
          value: "false"
        {{ end }}
        - name: DEPLOYMENT_PATH
          value: {{ .Values.deployment.path }}
        volumeMounts:
        {{- range $key, $value := .Values.apps.volume }}
        - name: {{ $key }}
          mountPath: /app
        {{- end }}
      volumes:
      - name: gatekeeper-config
        configMap:
          name: {{ .Release.Name }}-gatekeeper-config
      {{- range $key, $value := .Values.apps.volume }}
      - name: {{ $key }}
        persistentVolumeClaim:
          claimName: {{ $value.release }}
      {{- end }}
