# Generated by Django 2.2.13 on 2021-02-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
