# Generated by Django 2.2.13 on 2021-02-09 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_volume'),
        ('apps', '0002_apps_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settings', models.TextField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appinstance', to='apps.Apps')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appinstance', to='projects.Project')),
            ],
        ),
    ]
