# Generated by Django 2.2.13 on 2021-02-09 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_auto_20210209_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appinstance',
            old_name='lab_session_owner',
            new_name='owner',
        ),
    ]
