# Generated by Django 3.2.10 on 2021-12-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_auto_20211213_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apps',
            name='logo_file',
            field=models.ImageField(blank=True, null=True, upload_to='logos'),
        ),
    ]
