# Generated by Django 2.2.13 on 2021-02-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_auto_20210209_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='appinstance',
            name='keycloak_client_id',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
