# Generated by Django 2.2.13 on 2021-02-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_appinstance_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='path',
            field=models.CharField(blank=True, default='', max_length=512, null=True),
        ),
    ]
