# Generated by Django 3.2.11 on 2022-06-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_alter_apps_logo_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='user_can_create',
            field=models.BooleanField(default=True),
        ),
    ]
