# Generated by Django 2.2.13 on 2021-02-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_apps_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='exposed',
            field=models.CharField(default='external', max_length=10),
        ),
    ]
