# Generated by Django 2.2.13 on 2021-02-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_auto_20210209_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='appinstance',
            name='name',
            field=models.CharField(default='app_name', max_length=512),
        ),
        migrations.AddField(
            model_name='appinstance',
            name='parameters',
            field=models.TextField(blank=True, null=True),
        ),
    ]
