# Generated by Django 2.2.13 on 2021-02-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_auto_20210213_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='appinstance',
            name='app_dependencies',
            field=models.ManyToManyField(to='apps.AppInstance'),
        ),
        migrations.AddField(
            model_name='apps',
            name='category',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
