# Generated by Django 2.2.13 on 2021-02-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_volume'),
        ('apps', '0012_auto_20210213_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='appinstance',
            name='vol_dependencies',
            field=models.ManyToManyField(to='projects.Volume'),
        ),
    ]
