# Generated by Django 2.2.13 on 2021-02-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_metadata_modellog'),
        ('apps', '0013_appinstance_vol_dependencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='appinstance',
            name='model_dependencies',
            field=models.ManyToManyField(to='models.Model'),
        ),
    ]
