# Generated by Django 2.2.13 on 2021-02-13 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_appinstance_model_dependencies'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
            ],
        ),
        migrations.AlterField(
            model_name='apps',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='apps.AppCategories'),
        ),
    ]
