# Generated by Django 2.2.13 on 2021-02-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_auto_20210213_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='appcategories',
            name='slug',
            field=models.CharField(default='', max_length=512),
        ),
    ]
