# Generated by Django 2.2.13 on 2021-02-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0016_appcategories_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appcategories',
            name='id',
        ),
        migrations.AlterField(
            model_name='appcategories',
            name='slug',
            field=models.CharField(default='', max_length=512, primary_key=True, serialize=False),
        ),
    ]
