# Generated by Django 2.2.13 on 2021-02-15 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0017_auto_20210215_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apps',
            name='category',
        ),
    ]
