# Generated by Django 2.2.13 on 2021-02-15 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0018_remove_apps_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='apps.AppCategories'),
        ),
    ]
