# Generated by Django 2.2.13 on 2021-02-16 21:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0020_auto_20210216_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='apppermission',
            name='name',
            field=models.CharField(default='permission_name', max_length=512),
        ),
        migrations.AlterField(
            model_name='apppermission',
            name='projects',
            field=models.ManyToManyField(null=True, to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='apppermission',
            name='users',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
