# Generated by Django 2.2.13 on 2021-02-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0023_auto_20210217_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='appinstance',
            name='table_field',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='apps',
            name='table_field',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
