# Generated by Django 3.1.6 on 2021-02-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0024_auto_20210218_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appinstance',
            name='parameters',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
