# Generated by Django 3.1.6 on 2021-02-19 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0025_auto_20210219_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appinstance',
            name='vol_dependencies',
        ),
    ]
