# Generated by Django 3.1.6 on 2021-02-19 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0027_remove_appinstance_helmchart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apps',
            name='exposed',
        ),
        migrations.RemoveField(
            model_name='apps',
            name='path',
        ),
        migrations.RemoveField(
            model_name='apps',
            name='port',
        ),
        migrations.RemoveField(
            model_name='apps',
            name='schema',
        ),
        migrations.AlterField(
            model_name='apps',
            name='settings',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apps',
            name='table_field',
            field=models.TextField(blank=True, null=True),
        ),
    ]
