# Generated by Django 3.1.6 on 2021-02-20 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0028_auto_20210219_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appinstance',
            name='permission',
        ),
        migrations.AddField(
            model_name='apppermission',
            name='appinstance',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.appinstance'),
        ),
    ]
