# Generated by Django 3.1.6 on 2021-02-20 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0029_auto_20210220_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apppermission',
            name='appinstance',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permission', to='apps.appinstance'),
        ),
    ]
