# Generated by Django 3.1.6 on 2021-02-22 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0032_appinstance_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.IntegerField(verbose_name='cpu')),
                ('mem', models.IntegerField(verbose_name='memory')),
                ('gpu', models.IntegerField(verbose_name='gpu')),
                ('time', models.FloatField(verbose_name='timestamp')),
                ('appinstance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resourcedata', to='apps.appinstance')),
            ],
        ),
    ]
