# Generated by Django 3.1.6 on 2021-02-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0034_auto_20210222_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='appinstance',
            name='deleted_on',
            field=models.DateTimeField(null=True),
        ),
    ]
