# Generated by Django 3.1.6 on 2021-02-22 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0035_appinstance_deleted_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appinstance',
            name='keycloak_client_id',
        ),
    ]
