# Generated by Django 3.1.6 on 2021-02-22 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0036_remove_appinstance_keycloak_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcedata',
            name='cpu',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='resourcedata',
            name='gpu',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='resourcedata',
            name='mem',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='resourcedata',
            name='time',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='AppStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_type', models.CharField(default='app_name', max_length=15)),
                ('time', models.IntegerField()),
                ('info', models.JSONField(blank=True, null=True)),
                ('appinstance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='apps.appinstance')),
            ],
        ),
    ]
