# Generated by Django 3.1.6 on 2021-02-22 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0037_auto_20210222_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appstatus',
            name='time',
        ),
    ]
