# Generated by Django 3.1.6 on 2021-02-23 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0040_appstatus_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appstatus',
            options={'get_latest_by': 'time'},
        ),
    ]
