# Generated by Django 3.1.6 on 2021-03-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0041_auto_20210223_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='appinstance',
            name='open_field',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
