# Generated by Django 3.1.6 on 2021-03-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0042_appinstance_open_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appinstance',
            name='open_field',
        ),
        migrations.AddField(
            model_name='appinstance',
            name='name_field',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
