# Generated by Django 3.1.6 on 2021-03-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0043_auto_20210309_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='name_field',
            field=models.TextField(blank=True, null=True),
        ),
    ]
