# Generated by Django 3.1.6 on 2021-03-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0045_auto_20210309_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appinstance',
            name='table_field',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apps',
            name='table_field',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
