# Generated by Django 3.1.6 on 2021-03-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0046_auto_20210309_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appinstance',
            name='url',
        ),
        migrations.AlterField(
            model_name='appinstance',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
