# Generated by Django 3.1.6 on 2021-03-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0047_auto_20210309_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='logo',
            field=models.CharField(default='dist/applogos/stackn_logo_square.png', max_length=512),
        ),
        migrations.AlterField(
            model_name='appinstance',
            name='deleted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
