# Generated by Django 3.1.6 on 2021-03-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0009_auto_20210318_1401'),
        ('apps', '0048_auto_20210310_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appinstance',
            name='app_dependencies',
            field=models.ManyToManyField(blank=True, to='apps.AppInstance'),
        ),
        migrations.AlterField(
            model_name='appinstance',
            name='model_dependencies',
            field=models.ManyToManyField(blank=True, to='models.Model'),
        ),
    ]
