# Generated by Django 3.1.7 on 2021-04-09 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0051_auto_20210409_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appinstance',
            name='release_name',
        ),
    ]
