# Generated by Django 3.1.7 on 2021-05-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0053_auto_20210521_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='logo_file',
            field=models.FileField(blank=True, null=True, upload_to='apps/logos/'),
        ),
        migrations.AlterUniqueTogether(
            name='apps',
            unique_together={('slug', 'revision')},
        ),
    ]
