# Generated by Django 3.1.7 on 2021-05-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0054_auto_20210525_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='appinstance',
            name='access',
            field=models.CharField(blank=True, default='private', max_length=20, null=True),
        ),
    ]
