# Generated by Django 3.1.7 on 2021-06-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0055_appinstance_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='access',
            field=models.CharField(blank=True, default='public', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='apps',
            name='priority',
            field=models.IntegerField(default=100),
        ),
    ]
