# Generated by Django 3.1.7 on 2021-06-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0056_auto_20210608_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='appcategories',
            name='priority',
            field=models.IntegerField(default=100),
        ),
    ]
