# Generated by Django 3.1.7 on 2021-06-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0035_auto_20210607_2049'),
        ('apps', '0057_appcategories_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='projects',
            field=models.ManyToManyField(to='projects.Project'),
        ),
    ]
