# Generated by Django 3.2.11 on 2022-09-13 14:02

import django.db.models.deletion
import tagulous.models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppCategories',
            fields=[
                ('name', models.CharField(max_length=512)),
                ('priority', models.IntegerField(default=100)),
                ('slug', models.CharField(default='', max_length=512, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='AppInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access', models.CharField(blank=True, default='private', max_length=20, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('info', models.JSONField(blank=True, null=True)),
                ('name', models.CharField(default='app_name', max_length=512)),
                ('parameters', models.JSONField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('table_field', models.JSONField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'permissions': [('can_access_app', 'Can access app service')],
            },
        ),
        migrations.CreateModel(
            name='AppPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='permission_name', max_length=512)),
                ('public', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tagulous_AppInstance_tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('count', models.IntegerField(default=0, help_text='Internal counter of how many times this tag is in use')),
                ('protected', models.BooleanField(default=False, help_text='Will not be deleted when the count reaches 0')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
                'unique_together': {('slug',)},
            },
            bases=(tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.CreateModel(
            name='ResourceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.IntegerField()),
                ('gpu', models.IntegerField()),
                ('mem', models.IntegerField()),
                ('time', models.IntegerField()),
                ('appinstance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resourcedata', to='apps.appinstance')),
            ],
        ),
        migrations.CreateModel(
            name='AppStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.JSONField(blank=True, null=True)),
                ('status_type', models.CharField(default='app_name', max_length=15)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('appinstance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='apps.appinstance')),
            ],
            options={
                'get_latest_by': 'time',
            },
        ),
        migrations.CreateModel(
            name='Apps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_can_create', models.BooleanField(default=True)),
                ('access', models.CharField(blank=True, default='public', max_length=20, null=True)),
                ('chart', models.CharField(max_length=512)),
                ('chart_archive', models.FileField(blank=True, null=True, upload_to='apps/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('logo', models.CharField(default='', max_length=512)),
                ('logo_file', models.ImageField(blank=True, null=True, upload_to='apps/logos')),
                ('name', models.CharField(max_length=512)),
                ('priority', models.IntegerField(default=100)),
                ('revision', models.IntegerField(default=1)),
                ('settings', models.JSONField(blank=True, null=True)),
                ('slug', models.CharField(blank=True, max_length=512, null=True)),
                ('table_field', models.JSONField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='apps.appcategories')),
            ],
        ),
    ]
