# Generated by Django 4.0 on 2021-12-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apps',
            name='logo',
            field=models.CharField(default='apps/media/', max_length=512),
        ),
        migrations.AlterField(
            model_name='apps',
            name='logo_file',
            field=models.FileField(blank=True, null=True, upload_to='apps/media/logos/'),
        ),
    ]
