# Generated by Django 3.2.10 on 2021-12-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_alter_apps_logo_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apps',
            name='logo',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='apps',
            name='logo_file',
            field=models.FileField(blank=True, null=True, upload_to='apps/logos'),
        ),
    ]
