apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.release }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.release }}
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      release: {{ .Release.Name }}
      app: thingsboard
      project: {{ .Values.project.slug }}
      type: app
      pod: thingsboard
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8501"
      labels:
        release: {{ .Release.Name }}
        app: thingsboard
        project: {{ .Values.project.slug }}
        type: app
        pod: thingsboard
    spec:
      volumes:
      # - name: gatekeeper-config
      #   configMap:
      #     name: {{ .Release.Name }}-gatekeeper-config
      - name: tb-volume
      {{- range $key, $value := .Values.apps.volume }}
        persistentVolumeClaim:
          claimName: {{ $value.release }}
        {{- end }}
  
      containers:
      # - name: gatekeeper
      #   image: {{ .Values.gatekeeper.image }}
      #   imagePullPolicy: Always
      #   args:
      #     - --config=/etc/secrets/gatekeeper.yaml
      #   ports:
      #     - containerPort: {{ .Values.gatekeeper.port }}
      #   volumeMounts:
      #   - name: gatekeeper-config
      #     mountPath: /etc/secrets/
      - name: thingsboard
        image: thingsboard/tb-postgres:latest 
        imagePullPolicy: Always
        env:
        - name: TB_QUEUE_TYPE
          value: in-memory
        volumeMounts:
        - name: tb-volume
          mountPath: /data
      
        
