name: Python package

on:
  push:
    branches: [ master ]
    paths:
    - 'proto/**'
  pull_request:
    branches: [ master ]
    paths:
    - 'proto/**'
jobs:
  build:

    env:
      working-directory: ./proto

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      working-directory: ${{env.working-directory}}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      working-directory: ${{env.working-directory}}
      run: |
        python -m pip install --upgrade pip
        pip install .
    - name: Lint with flake8
      working-directory: ${{env.working-directory}}
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      working-directory: ${{env.working-directory}}
      run: |
        pip install pytest
        pytest
