name: Chart Controller CI

on:
  push:
    branches: '*'
    paths:
    - 'components/**'
  pull_request:
    branches: '*'
    paths:
    - 'components/**'

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_URL: scaleoutsystems
      working-directory: ./components/chart-controller

    steps:
    - uses: actions/checkout@v2

    - name: Setup variables
      id: wf-vars
      run: |
        BRANCH=${GITHUB_REF##*/}
        VERSION=${GITHUB_REF##*-}
        IMAGE_NAME="chart-controller"
        IMAGE_TAG="$BRANCH"
        echo ::set-output name=IMAGE_NAME::$IMAGE_NAME
        echo ::set-output name=IMAGE_TAG::$IMAGE_TAG
    - name: docker login
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: docker build chart-controller
      env:
        DOCKER_URL: scaleoutsystems
      working-directory: ${{env.working-directory}}
      run: |
        docker build -t $DOCKER_URL/${{ steps.wf-vars.outputs.IMAGE_NAME }}:${{ steps.wf-vars.outputs.IMAGE_TAG }} .

    - name: docker push
      env:
        DOCKER_URL: scaleoutsystems
      working-directory: ${{env.working-directory}}
      run: |
        docker push $DOCKER_URL/${{ steps.wf-vars.outputs.IMAGE_NAME }}:${{ steps.wf-vars.outputs.IMAGE_TAG }}
