name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    env:
      working-directory: ./proto

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      working-directory: ${{env.working-directory}}
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - name: Install dependencies
      working-directory: ${{env.working-directory}}
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Build and publish
      working-directory: ${{env.working-directory}}
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*
