# Generated by Django 3.2.11 on 2022-01-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_auto_20220125_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='version',
            field=models.CharField(default='1.0', max_length=255),
        ),
    ]
