# Generated by Django 4.1.7 on 2023-07-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0010_alter_model_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='objecttype',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
